DATASET_CANDIDATE="data/output/H36M_VAE/TEST/keypoints"
DATASET_CROPPED="data/H36Mtest"
DATASET_ORIGNAL="data/H36Mtest_original_noreps"
DATASET_CANDIDATE_MAX=35000

DATASET_REFERENCE="/Volumes/ElementsDat/pose/H36M/H36M"
DATASET_REFERENCE_MAX=200000

NUMJOINTS=15

python FPD_H36M.py $DATASET_CANDIDATE $DATASET_CROPPED $DATASET_ORIGNAL $DATASET_CANDIDATE_MAX $DATASET_REFERENCE $DATASET_REFERENCE_MAX $NUMJOINTS
