DATASET_CROPPED="data/ECCV18OP_crop"
DATASET_ORIGINAL="data/ECCV18OP_onlyused"
#DATASET_ORIGINAL="/Volumes/ElementsDat/pose/H36M/ECCV2018/ECCV18OD_no_sufix"
OUTPUTPATH="data/output/ECCV18OP_II"
DATASET_CHARADE="/Users/rtous/DockerVolume/charade_full/input/keypoints"
DATASET_CHARADE_IMAGES="/Users/rtous/DockerVolume/charade_full/input/images"
DATASET_TEST="dynamicData/ECCV18OD_test_crop"
DATASET_TEST_IMAGES="/Volumes/ElementsDat/pose/H36M/ECCV2018/ECCV18_Challenge/Train/IMG/"
BODY_MODEL="OPENPOSE_25"
DATASET_MODULE="datasetBasic"
MODEL="models"
#MODEL="modelsECCV18OP"
python train.py $DATASET_CROPPED $DATASET_ORIGINAL $OUTPUTPATH $DATASET_CHARADE $DATASET_CHARADE_IMAGES $DATASET_TEST $DATASET_TEST_IMAGES $BODY_MODEL $DATASET_MODULE $MODEL
#python test13_plus_regression_like_context_encoder.py $DATASET_CROPPED $DATASET_ORIGINAL $OUTPUTPATH $DATASET_CHARADE $DATASET_CHARADE_IMAGES $DATASET_TEST $DATASET_TEST_IMAGES

